name: "bde_assignment_3"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by dbt clean
  - "target"
  - "dbt_packages"

models:
  bde_assignment_3:
    bronze:
      +materialized: table
      +schema: bronze2  # Set schema to bronze2
    silver:
      +materialized: table
      +schema: silver  # Set schema to silver
    gold:
      star:
        +materialized: table
        +schema: gold  # Set schema to gold
      mart:
        +materialized: view
        +schema: gold  # Set schema to gold

snapshots:
  bde_assignment_3:
    +schema: silver

